### ISSUE TITLE
Deadlock on multiple concurrent resolutions

### ISSUE THREAD

**Issue by richarddd** [Gelbpunkt/hyper-trust-dns#13]
I'm in a situation where i need to fire of lots of concurrent requests to same host. Using hyper hickory resolver introduces deadlocks. Using over 200-500 request creates a deadlock causing the process to hang. The builtin resolver has the downside of spawning one new thread per DNS resolution but at least works. Some sort of semaphore should probably help here.

Also, performance is severely degraded vs GAI Resolver for few requests:

 ```shell
target/release/client-hyper 'https://www.amazon.com' 10
0 - 200
1 - 200
2 - 200
3 - 200
4 - 200
5 - 200
6 - 200
7 - 200
8 - 200
9 - 200
Time elapsed: 226.90825ms
```

 ```shell
target/release/client-hyper --hickory 'https://www.amazon.com' 10
0 - 200
1 - 200
2 - 200
3 - 200
4 - 200
5 - 200
6 - 200
7 - 200
8 - 200
9 - 200
Time elapsed: 319.818166ms
```

Reproducable:
**Cargo.toml**
```toml
[package]
name = "client-hyper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
hyper = { version = "1", features = ["client"] }
hyper-util = { version = "*", features = [
    "tokio",
    "client",
    "client-legacy",
    "http1",
    "http2",
] }
tokio = { version = "1", features = ["full"] }
http-body-util = "*"
hyper-rustls = { version = "0.27", default-features = false, features = [
    "http2",
    "http1",
    "webpki-roots",
    "webpki-tokio",
    "ring",
] }
rustls = { version = "0.23", default-features = false, features = [
    "tls12",
    "ring",
] }
tokio-rustls = { version = "0.26", default-features = false, features = [
    "tls12",
    "ring",
] }
rustls-pki-types = "1.10.1"
webpki-roots = "0.26.7"
console-subscriber = "0.4.1"
hyper-hickory = { version = "0.7.0", features = [] }
hickory-resolver = "0.24.2"

```

**main.rs**
```rust
use anyhow::Result;
use http_body_util::combinators::BoxBody;
use http_body_util::{BodyExt, Full};
use hyper::body::Bytes;
use hyper::Request;
use hyper_util::client::legacy::connect::Connect;
use hyper_util::client::legacy::Client;
use hyper_util::rt::{TokioExecutor, TokioTimer};
use rustls::crypto::ring;
use rustls::{ClientConfig, RootCertStore};
use std::convert::Infallible;
use std::error::Error;
use std::num::NonZeroUsize;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Arc;
use std::time::Duration;

use webpki_roots::TLS_SERVER_ROOTS;

fn main() -> Result<(), Box<dyn Error>> {
    let cpus = std::thread::available_parallelism().map_or(1, NonZeroUsize::get);
    tokio::runtime::Builder::new_multi_thread()
        .worker_threads(cpus)
        .enable_all()
        .build()
        .unwrap()
        .block_on(async { async_main().await })
}

async fn async_main() -> Result<(), Box<dyn Error>> {
    let mut use_http2 = true; // default to HTTP/2
    let mut use_hickory = false;
    let mut url = None;
    let mut num_requests = None;
    let mut args = std::env::args(); // Skip program name
    let program_name = args.next().unwrap();

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--http2" => use_http2 = true,
            "--http" => use_http2 = false,
            "--hickory" => use_hickory = true,
            _ => {
                if url.is_none() {
                    url = Some(arg);
                } else if num_requests.is_none() {
                    num_requests = Some(arg.parse::<usize>().unwrap_or_else(|_| {
                        eprintln!("num_requests must be a positive number");
                        std::process::exit(1);
                    }));
                } else {
                    print_usage(&program_name);
                    std::process::exit(1);
                }
            }
        }
    }

    let url = url.unwrap_or_else(|| {
        print_usage(&program_name);
        std::process::exit(1);
    });
    let num_requests = num_requests.unwrap_or_else(|| {
        print_usage(&program_name);
        std::process::exit(1);
    });

    let mut root_certificates = RootCertStore::empty();

    for cert in TLS_SERVER_ROOTS.iter().cloned() {
        root_certificates.roots.push(cert)
    }

    let builder = ClientConfig::builder_with_provider(ring::default_provider().into());

    let client_config = builder
        .with_safe_default_protocol_versions()
        .expect("TLS configuration failed")
        .with_root_certificates(root_certificates)
        .with_no_client_auth();

    let builder = hyper_rustls::HttpsConnectorBuilder::new()
        .with_tls_config(client_config)
        .https_or_http();

    if use_hickory {
        let mut hickory_connector =
            hyper_hickory::TokioHickoryResolver::default().into_http_connector();
        hickory_connector.enforce_http(false);
        let https = if use_http2 {
            builder.enable_http2().wrap_connector(hickory_connector)
        } else {
            builder.enable_http1().wrap_connector(hickory_connector)
        };
        send_requests(https, &url, num_requests).await?;
    } else {
        let https = if use_http2 {
            builder.enable_http2().build()
        } else {
            builder.enable_http1().build()
        };
        send_requests(https, &url, num_requests).await?;
    };

    Ok(())
}

fn print_usage(program_name: &str) {
    eprintln!(
        "Usage: {} [--http2|--http] [--hickory] <url> <num_requests>",
        program_name
    );
}

async fn send_requests<T>(https: T, url: &str, num_requests: usize) -> Result<(), Box<dyn Error>>
where
    T: Connect + Clone + Send + Sync + 'static,
{
    let client: Client<T, _> = Client::builder(TokioExecutor::new())
        .pool_idle_timeout(Duration::from_secs(30))
        .pool_timer(TokioTimer::new())
        .build(https);

    let start = std::time::Instant::now();
    let mut futures = Vec::new();
    let completed = Arc::new(AtomicUsize::new(0));

    for _ in 0..num_requests {
        let client = client.clone();
        let completed = completed.clone();
        let url = url.to_string();

        futures.push(tokio::task::spawn(async move {
            let request: Request<BoxBody<Bytes, Infallible>> = Request::builder()
                .uri(url)
                .body(BoxBody::new(Full::default()))?;

            let response = client.request(request).await?;
            let status = response.status();

            let _ = response.collect().await?.to_bytes();
            println!(
                "{} - {:?}",
                completed.fetch_add(1, Ordering::Relaxed),
                status
            );

            Ok::<_, Box<dyn Error + Send + Sync>>(())
        }));
    }

    for future in futures {
        let _ = future.await?;
    }
    let duration = start.elapsed();
    println!("Time elapsed: {:?}", duration);

    Ok(())
}

```
